### ISSUE TITLE
JPype1-py3 error

### ISSUE THREAD

**Issue by kahyung** [kahyung/KoNLPy#1]
*****$ pip3 install JPype1-py3 
Collecting JPype1-py3
  Using cached JPype1-py3-0.5.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/_8/jblmyjh97p1c_ng5nlqr2srh0000gn/T/pip-build-ibtivja2/JPype1-py3/setup.py", line 451, in <module>
        config = DarwinJDKFinder()
      File "/private/var/folders/_8/jblmyjh97p1c_ng5nlqr2srh0000gn/T/pip-build-ibtivja2/JPype1-py3/setup.py", line 290, in __init__
        java_home = self.find_jdk_home()
      File "/private/var/folders/_8/jblmyjh97p1c_ng5nlqr2srh0000gn/T/pip-build-ibtivja2/JPype1-py3/setup.py", line 349, in find_jdk_home
        raise NoJDKError(visited_folders)
    __main__.NoJDKError: No JDK found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_8/jblmyjh97p1c_ng5nlqr2srh0000gn/T/pip-build-ibtivja2/JPype1-py3/setup.py", line 468, in <module>
        .format('\n'.join(ex.possible_homes)))
    RuntimeError: No Java/JDK could be found. I looked in the following directories:
    
    /Library/Java/JavaVirtualMachines/1.6.0.jdk
    /Library/Java/Home
    
    Please check that you have it installed.
    
    If you have and the destination is not in the above list, please find out where your java's home is, set your JAVA_HOME environment variable to that path and retry the installation.
    If this still fails please open a ticket or create a pull request with a fix on github:
    https://github.com/tcalmant/jpype/
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_8/jblmyjh97p1c_ng5nlqr2srh0000gn/T/pip-build-ibtivja2/JPype1-py3/

**Comment by kahyung** [comment]
Here is the installation guide (from http://konlpy.org/en/v0.4.4/install/#id1)

Mac OS
Install dependencies
$ pip install JPype1         # Python 2.x
$ pip3 install JPype1-py3    # Python 3.x
Install KoNLPy
$ pip install konlpy         # Python 2.x
$ pip3 install konlpy        # Python 3.x
Install MeCab (optional)
$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)
